apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gppbq360n-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gppbq360n-java-quarkus-gitops